name: CI/CD

on:
  push:
    branches: [dev, staging, main]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

concurrency:
  group: cicd-${{ github.ref }}
  cancel-in-progress: true

env:
  AWS_REGION: ap-northeast-1
  DOCKERFILE: Dockerfile

jobs:
  deploy:
    name: Deploy (${{ matrix.env }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - branch: dev
            env: dev
            tf_dir: dev
            ecr_repo: myapp-dev
            environment: dev
          - branch: staging
            env: staging
            tf_dir: staging
            ecr_repo: myapp-staging
            environment: staging
          - branch: main
            env: prod
            tf_dir: prod
            ecr_repo: myapp-prod
            environment: prod
    if: github.ref == format('refs/heads/{0}', matrix.branch)
    environment: ${{ matrix.environment }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Ensure ECR repository exists
        env:
          REPO: ${{ matrix.ecr_repo }}
        run: |
          aws ecr describe-repositories --repository-names "$REPO" >/dev/null 2>&1 || \
          aws ecr create-repository --repository-name "$REPO" >/dev/null

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ steps.login-ecr.outputs.registry }}/${{ matrix.ecr_repo }}
          tags: |
            type=sha,format=short,prefix=${{ matrix.env }}-
            type=raw,value=${{ matrix.env }}-latest

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ env.DOCKERFILE }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Set image tag output (env-shortsha)
        id: image
        env:
          ENV: ${{ matrix.env }}
        run: |
          SHORT_SHA="${GITHUB_SHA::7}"
          echo "tag=${ENV}-${SHORT_SHA}" >> "$GITHUB_OUTPUT"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Terraform Init (local for dev)
        if: matrix.env == 'dev'
        working-directory: terraform/${{ matrix.tf_dir }}
        run: terraform init -input=false -no-color

      - name: Terraform Init (S3 backend)
        if: matrix.env != 'dev'
        working-directory: terraform/${{ matrix.tf_dir }}
        env:
          TF_BACKEND_BUCKET: ${{ secrets.TF_BACKEND_BUCKET }}
          TF_BACKEND_DDB_TABLE: ${{ secrets.TF_BACKEND_DDB_TABLE }}
        run: |
          terraform init -input=false -no-color \
            -backend-config="bucket=${TF_BACKEND_BUCKET}" \
            -backend-config="key=myapp/${{ matrix.env }}/terraform.tfstate" \
            -backend-config="region=${{ env.AWS_REGION }}" \
            -backend-config="dynamodb_table=${TF_BACKEND_DDB_TABLE}"

      - name: Terraform Validate
        working-directory: terraform/${{ matrix.tf_dir }}
        run: terraform validate -no-color

      - name: Terraform Plan
        working-directory: terraform/${{ matrix.tf_dir }}
        run: terraform plan -input=false -no-color -var="image_tag=${{ steps.image.outputs.tag }}"

      - name: Terraform Apply
        working-directory: terraform/${{ matrix.tf_dir }}
        run: terraform apply -input=false -auto-approve -no-color -var="image_tag=${{ steps.image.outputs.tag }}" 