name: CI/CD

on:
  push:
    branches: [dev, staging, main]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

concurrency:
  group: cicd-${{ github.ref }}
  cancel-in-progress: true

env:
  AWS_REGION: ap-northeast-1
  DOCKERFILE: Dockerfile

jobs:
  deploy:
    name: Deploy (${{ matrix.env }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - branch: dev
            env: dev
            tf_dir: dev
            ecr_repo: myapp-dev
            environment: dev
          - branch: staging
            env: staging
            tf_dir: staging
            ecr_repo: myapp-staging
            environment: staging
          - branch: main
            env: prod
            tf_dir: prod
            ecr_repo: myapp-prod
            environment: prod
    if: github.ref == format('refs/heads/{0}', matrix.branch)
    environment: ${{ matrix.environment }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Optional: prepare toolchains for language builds outside Docker if needed
      - name: Set up Java (Gradle projects)
        if: hashFiles('**/build.gradle*') != ''
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Ensure ECR repository exists
        env:
          REPO: ${{ matrix.ecr_repo }}
        run: |
          aws ecr describe-repositories --repository-names "$REPO" >/dev/null 2>&1 || \
          aws ecr create-repository --repository-name "$REPO" >/dev/null

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ steps.login-ecr.outputs.registry }}/${{ matrix.ecr_repo }}
          tags: |
            type=sha,format=short,prefix=${{ matrix.env }}-
            type=raw,value=${{ matrix.env }}-latest

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ env.DOCKERFILE }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Set image tag output (env-shortsha)
        id: image
        env:
          ENV: ${{ matrix.env }}
        run: |
          SHORT_SHA="${GITHUB_SHA::7}"
          echo "tag=${ENV}-${SHORT_SHA}" >> "$GITHUB_OUTPUT"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Terraform Init (S3 backend)
        working-directory: terraform
        env:
          TF_BACKEND_BUCKET: ${{ secrets.TF_BACKEND_BUCKET }}
          TF_BACKEND_DDB_TABLE: ${{ secrets.TF_BACKEND_DDB_TABLE }}
        run: |
          terraform init -input=false -no-color \
            -backend-config="bucket=${TF_BACKEND_BUCKET}" \
            -backend-config="key=myapp/${{ matrix.env }}/terraform.tfstate" \
            -backend-config="region=${{ env.AWS_REGION }}" \
            -backend-config="dynamodb_table=${TF_BACKEND_DDB_TABLE}"

      - name: Select/Create workspace
        working-directory: terraform
        run: |
          terraform workspace select ${{ matrix.env }} 2>/dev/null || terraform workspace new ${{ matrix.env }}

      - name: Terraform Validate
        working-directory: terraform
        run: terraform validate -no-color

      - name: Terraform Plan
        working-directory: terraform
        run: |
          terraform plan -input=false -no-color \
            -var="aws_region=${{ env.AWS_REGION }}" \
            -var="ecr_repo_name=${{ matrix.ecr_repo }}" \
            -var="ecs_cluster_name=${{ matrix.ecr_repo }}-cluster" \
            -var="ecs_service_name=${{ matrix.ecr_repo }}-service" \
            -var="image_tag=${{ steps.image.outputs.tag }}"

      - name: Terraform Apply
        working-directory: terraform
        run: |
          terraform apply -input=false -auto-approve -no-color \
            -var="aws_region=${{ env.AWS_REGION }}" \
            -var="ecr_repo_name=${{ matrix.ecr_repo }}" \
            -var="ecs_cluster_name=${{ matrix.ecr_repo }}-cluster" \
            -var="ecs_service_name=${{ matrix.ecr_repo }}-service" \
            -var="image_tag=${{ steps.image.outputs.tag }}"

name: CI/CD Pipeline for Golang on ECS

on:
  push:
    branches:
      - main
      - develop
      - 'feature/*'

env:
  AWS_REGION: ap-northeast-1
  ECR_REPOSITORY: your-ecr-repo-name
  ECS_CLUSTER: your-ecs-cluster
  ECS_SERVICE: your-ecs-service
  TF_WORKING_DIR: terraform

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      TF_WORKING_DIR: ${{ github.ref == 'refs/heads/main' && 'terraform/prod' || github.ref == 'refs/heads/develop' && 'terraform/staging' || startsWith(github.ref, 'refs/heads/feature/') && 'terraform/dev' || 'terraform/dev' }}
      ECR_REPOSITORY: ${{ github.ref == 'refs/heads/main' && 'myapp-prod' || github.ref == 'refs/heads/develop' && 'myapp-staging' || startsWith(github.ref, 'refs/heads/feature/') && 'myapp-dev' || 'myapp-dev' }}
      ECS_CLUSTER: ${{ github.ref == 'refs/heads/main' && 'myapp-prod-cluster' || github.ref == 'refs/heads/develop' && 'myapp-staging-cluster' || startsWith(github.ref, 'refs/heads/feature/') && 'myapp-dev-cluster' || 'myapp-dev-cluster' }}
      ECS_SERVICE: ${{ github.ref == 'refs/heads/main' && 'myapp-prod-service' || github.ref == 'refs/heads/develop' && 'myapp-staging-service' || startsWith(github.ref, 'refs/heads/feature/') && 'myapp-dev-service' || 'myapp-dev-service' }}
      AWS_REGION: ap-northeast-1

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push Docker image to ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG .
        docker push $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      working-directory: ${{ env.TF_WORKING_DIR }}
      run: terraform init

    - name: Terraform Plan
      working-directory: ${{ env.TF_WORKING_DIR }}
      run: terraform plan -var="image_tag=${{ github.sha }}" -var="ecr_repo_name=${{ env.ECR_REPOSITORY }}" -var="ecs_cluster_name=${{ env.ECS_CLUSTER }}" -var="ecs_service_name=${{ env.ECS_SERVICE }}"

    - name: Terraform Apply
      working-directory: ${{ env.TF_WORKING_DIR }}
      run: terraform apply -auto-approve -var="image_tag=${{ github.sha }}" -var="ecr_repo_name=${{ env.ECR_REPOSITORY }}" -var="ecs_cluster_name=${{ env.ECS_CLUSTER }}" -var="ecs_service_name=${{ env.ECS_SERVICE }}"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ env.AWS_REGION }} 